# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

---

# ci:
#   skip: []

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Changes tabs to spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.1
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        # exclude: (test_.*\.py)$
        additional_dependencies: [tomli]

  - repo: https://github.com/PyCQA/doc8/
    rev: v1.1.1
    hooks:
      - id: doc8
        alias: doc8-lint
        require_serial: false
        additional_dependencies: [tomli]
        args: []

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        require_serial: false
        args: [-x, --severity=warning]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        require_serial: false
        args: [-S, '.git,third_party', -I, .codespell.allow]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        require_serial: false

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        args: [-S, -l, '120']
        additional_dependencies: [black==22.10.0]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus, --keep-mock]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--docstring-convention, google]
        name: flake8-strict
        # exclude: (test_.*\.py)$
        additional_dependencies: [flake8-breakpoint, flake8-builtins, flake8-comprehensions, flake8-continuation,
                                  flake8-docstrings, flake8-eradicate, flake8-mutable, flake8-return, pep8-naming,
                                  flake8-secure-coding-standard]

  - repo: https://github.com/pycqa/pylint
    rev: v2.16.0b1
    hooks:
      - id: pylint
        name: pylint-strict
        # exclude: (test_.*\.py)$
        args: [--score=n, --load-plugins=pylint_secure_coding_standard]
        additional_dependencies: [flask, flask-wtf, pylint-secure-coding-standard]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
